### ISSUE TITLE
The bug regarding distance settings

### ISSUE THREAD

**Issue by sisheng36** [mouldybread/hlk_ld2402_esphome#7]
hi，bro.I have been troubled for several months about connecting LD2402 to esphome. Thank you very much for your configuration file.I found 2 bugs about this module。
1.The maximum distance can only be set to 5m, even if I have changed the .yaml, the XXX.bin generated by esphome will still control the module to only send a prompt when a person is detected within 5 meters.I am now reconnecting my esp8266 by removing the LD2402 module hou and setting the maximum distance using usb-ttl, and now it is able to give a hint for movement up to 5 meters away
2.My living room is 7 meters long, but "Presence" prompts "off" and "Micromovement" prompts "on" 5 meters away, which is wrong, I think it would be better to change "Presence" to "Sit still", use "IO" to connect "IO12" to prompt "Presence".like this
binary_sensor:
  - platform: gpio
    pin: GPIO12
    name: "presence"
    device_class: `motion
By the way, I am the first one to light up the stars.Thank you again for connecting the LD2402 module to esphome.

**Comment by mouldybread** [comment]
Hey, no worries - happy it helped someone else!

Firstly you're entirely right, that config is not pushed to the module at all but is supposed to be used internally. In the current implementation it should be fine to leave the module setting at the maximum. ESPHome knows each gate is 0.75 meters so the software can ignore gates outside of the configured range, even if they exceed threshold values, and won't change the state of a sensor. I can see that this might cause problems if you are using the output pin though, in my case I am not so I didn't consider it.

For reference the manual from hilink states that in wall-mounted configuration this module can detect moving presence up to 10 meters, micro-movement presence up to 6 meters, and static (non-moving) presence up to 5 meters. With the values for ceiling mount being 5, 4 and 3 respectively. The AI garbled that part pretty badly in the main documentation.

I've added code to the testing branch. Firstly to write the "max_distance" parameter to the module, and secondly to give you the option of configuring the maximum detection range in the software. To try it out:

```yaml
external_components:
  - source:
      type: git
      url: (component url)
     ref: Testing
    refresh: 0ms`
```
```yaml
hlk_ld2402:
  uart_id: uart_bus
  id: radar_sensor
  max_distance: 5.0  # Maximum overall detection range
  # Optional: Configure specific ranges for different detection types
  movement_range: 10.0  # Maximum range for motion detection (up to 10m)
  micromovement_range: 6.0  # Maximum range for micromotion detection (up to 6m)
  static_range: 5.0  # Maximum range for static presence detection (up to 5m)
  timeout: 5
```
The refresh: parameter makes sure that it fully refreshes the code from github every compilation, but it can add some time to the process, so remember to remove it when you're done testing. 

I'm working on a different model today so I can't test it myself right now, it does compile though. Let me know how it goes, and worst case I'll do some testing myself in a couple of days when I'm done with the LD2401.

With regards to your second observation, I'll rename Presence to Static Presence in the testing branch so that if you are using the pin you can define a Presence sensor based on micromovement detection direct from the hardware.

I'm all for simplicity so perhaps if you can get it configured how you want it, it would really make more sense to ditch the custom component entirely and just read the output pin. I'm in the midst of implementing other modules and I'm wondering if duplicating so much logic outside of the modules really makes sense when I could just be configuring them and then reading the output pin. This is definitely one of my favorites so far, shame it lacks bluetooth.
